// Dummy data for freelancers
const dummyFreelancers = [
  {
    id: 1,
    name: "Priya Sharma",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    specialization: "Full Stack Developer",
    rating: 4.9,
    hourly_rate: 35,
    skills: ["React", "Node.js", "MongoDB", "Express", "TypeScript"],
    completed_projects: 47,
    success_rate: 98,
    response_time: "1 hour",
    previously_worked: true,
    top_rated: true,
    isTalentRise: false
  },
  {
    id: 2,
    name: "Rahul Kapoor",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    specialization: "UI/UX Designer",
    rating: 4.7,
    hourly_rate: 30,
    skills: ["Figma", "Adobe XD", "Sketch", "User Research", "Wireframing"],
    completed_projects: 31,
    success_rate: 95,
    response_time: "2 hours",
    previously_worked: false,
    top_rated: true,
    isTalentRise: false
  },
  {
    id: 3,
    name: "Anika Patel",
    avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    specialization: "Mobile App Developer",
    rating: 4.8,
    hourly_rate: 40,
    skills: ["Flutter", "React Native", "Firebase", "Swift", "Kotlin"],
    completed_projects: 23,
    success_rate: 100,
    response_time: "30 minutes",
    previously_worked: true,
    top_rated: false,
    isTalentRise: false
  },
  {
    id: 4,
    name: "Vikram Singh",
    avatar: "https://randomuser.me/api/portraits/men/91.jpg",
    specialization: "DevOps Engineer",
    rating: 4.6,
    hourly_rate: 45,
    skills: ["Docker", "Kubernetes", "AWS", "CI/CD", "Terraform"],
    completed_projects: 18,
    success_rate: 94,
    response_time: "3 hours",
    previously_worked: false,
    top_rated: false,
    isTalentRise: false
  },
  {
    id: 5,
    name: "Meera Desai",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    specialization: "Blockchain Developer",
    rating: 4.9,
    hourly_rate: 55,
    skills: ["Solidity", "Web3.js", "Ethereum", "Smart Contracts", "DApps"],
    completed_projects: 12,
    success_rate: 100,
    response_time: "1 hour",
    previously_worked: false,
    top_rated: true,
    isTalentRise: false
  },
  {
    id: 6,
    name: "Arjun Mehta",
    avatar: "https://randomuser.me/api/portraits/men/22.jpg",
    specialization: "Data Scientist",
    rating: 4.8,
    hourly_rate: 50,
    skills: ["Python", "TensorFlow", "Pandas", "Data Visualization", "Machine Learning"],
    completed_projects: 27,
    success_rate: 96,
    response_time: "2 hours",
    previously_worked: true,
    top_rated: true,
    isTalentRise: false
  },
  {
    id: 7,
    name: "Zara Khan",
    avatar: "https://randomuser.me/api/portraits/women/57.jpg",
    specialization: "Content Writer",
    rating: 4.5,
    hourly_rate: 25,
    skills: ["SEO Writing", "Blog Posts", "Technical Writing", "Copywriting", "Editing"],
    completed_projects: 52,
    success_rate: 92,
    response_time: "45 minutes",
    previously_worked: false,
    top_rated: false,
    isTalentRise: false
  },
  {
    id: 8,
    name: "Rohan Joshi",
    avatar: "https://randomuser.me/api/portraits/men/46.jpg",
    specialization: "Graphic Designer",
    rating: 4.7,
    hourly_rate: 35,
    skills: ["Adobe Photoshop", "Illustrator", "Branding", "Logo Design", "Print Design"],
    completed_projects: 38,
    success_rate: 97,
    response_time: "1 hour",
    previously_worked: true,
    top_rated: true,
    isTalentRise: false
  },
  // TalentRise Student Freelancers
  {
    id: 9,
    name: "Aarav Gupta",
    avatar: "https://randomuser.me/api/portraits/men/25.jpg",
    specialization: "Computer Science Student",
    rating: 4.3,
    hourly_rate: 18,
    skills: ["Python", "Java", "Web Development", "Algorithms"],
    completed_projects: 5,
    success_rate: 92,
    response_time: "4 hours",
    previously_worked: false,
    top_rated: false,
    isTalentRise: true,
    university: "Indian Institute of Technology Delhi",
    availableHours: "15-20",
    academicProjects: [
      "AI-based Attendance System",
      "E-commerce Platform Prototype"
    ]
  },
  {
    id: 10,
    name: "Neha Sharma",
    avatar: "https://randomuser.me/api/portraits/women/30.jpg",
    specialization: "Design Student",
    rating: 4.5,
    hourly_rate: 20,
    skills: ["Figma", "UI/UX", "Adobe XD", "Wireframing"],
    completed_projects: 8,
    success_rate: 95,
    response_time: "3 hours",
    previously_worked: true,
    top_rated: false,
    isTalentRise: true,
    university: "National Institute of Design",
    availableHours: "10-15",
    academicProjects: [
      "Mobile App Design for Campus Events",
      "Accessibility-focused UI Kit"
    ]
  },
  {
    id: 11,
    name: "Rohan Mehta",
    avatar: "https://randomuser.me/api/portraits/men/35.jpg",
    specialization: "Engineering Student",
    rating: 4.2,
    hourly_rate: 15,
    skills: ["CAD", "3D Modeling", "Python", "Technical Writing"],
    completed_projects: 3,
    success_rate: 88,
    response_time: "6 hours",
    previously_worked: false,
    top_rated: false,
    isTalentRise: true,
    university: "Delhi Technological University",
    availableHours: "12-18",
    academicProjects: [
      "Smart Irrigation System Design",
      "CAD Modeling for Mechanical Parts"
    ]
  },
  {
    id: 12,
    name: "Priya Joshi",
    avatar: "https://randomuser.me/api/portraits/women/28.jpg",
    specialization: "Marketing Student",
    rating: 4.4,
    hourly_rate: 16,
    skills: ["Social Media", "Content Writing", "SEO", "Canva"],
    completed_projects: 6,
    success_rate: 90,
    response_time: "5 hours",
    previously_worked: true,
    top_rated: false,
    isTalentRise: true,
    university: "Symbiosis Institute of Media Studies",
    availableHours: "8-12",
    academicProjects: [
      "Social Media Campaign for NGO",
      "Market Research Analysis"
    ]
  }
];

export default dummyFreelancers;